version: "3.4"

name: postsbymarko-docker-compose

networks:
  beNetwork:
  feNetwork:
  
services:
  #DATABASE
  sqlserver:
    container_name: PostsByMarko.SqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    networks:
      - beNetwork
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SQL_PASSWORD}
   
  #HOST
  host:
    container_name: PostsByMarko.Host
    build:
      dockerfile: src/PostsByMarko.Host/Dockerfile
    ports:
      - ${HOST_PORT}:${HOST_PORT}
    depends_on:
      - sqlserver
    networks:
      - beNetwork
      - feNetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:${HOST_PORT}

  #CLIENT
  client:
    container_name: PostsByMarko.Client
    build:
      dockerfile: src/PostsByMarko.Client/Dockerfile
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    depends_on:
      - host
    volumes:
      - ./src:/app/src
    networks:
      - feNetwork
    environment:
      - NODE_ENV=docker

