version: "3.4"

name: posts-docker-compose

networks:
  postsBackendNetwork:
  postsFrontendNetwork:
  
services:
  #DATABASE
  PostsByMarko.Database:
    container_name: postsbymarkodb
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - 1433:1433
    networks:
      - postsBackendNetwork
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
   
  #WEB API
  PostsByMarko.Host:
    container_name: postsbymarkohost
    build:
      dockerfile: PostsByMarko.Host/Dockerfile
    ports:
      - 7171:80
    depends_on:
      - PostsByMarko.Database
    networks:
      - postsBackendNetwork
      - postsFrontendNetwork
    environment:
      - DB_HOST=postsdb
      - DB_NAME=PostsDB
      - DB_USER_ID=sa
      - IS_IN_DOCKER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}

  #CLIENT
  PostsByMarko.Client:
    container_name: postsbymarkoclient
    build:
      dockerfile: PostsByMarko.Client/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - PostsByMarko.Host
    volumes:
      - ./src:/app/src
    networks:
      - postsFrontendNetwork
    environment:
      - NODE_ENV=development

