version: "3.4"

name: posts-docker-compose

networks:
  fluentd:
  postsBackendNetwork:
  postsFrontendNetwork:
  elasticsearch:
  kibana:

services:
  #DATABASE
  postsdb:
    container_name: posts-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    networks:
      - postsBackendNetwork
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@Marko123

  #WEB API
  aspnetserver:
    container_name: posts-server
    image: ${DOCKER_REGISTRY-}aspnetserver:latest
    build:
      context: .
      dockerfile: aspnetserver/Dockerfile
    ports:
      - 7171:80
    depends_on:
      - postsdb
      - fluentd
    networks:
      - postsBackendNetwork
      - postsFrontendNetwork
      - fluentd
    environment:
      - DB_HOST=postsdb
      - DB_NAME=PostsDB
      - DB_USER_ID=sa
      - MSSQL_SA_PASSWORD=@Marko123
      - ASPNETCORE_ENVIRONMENT=Development
      - IS_IN_DOCKER=true

  #CLIENT
  reactclient:
    container_name: posts-client
    image: ${DOCKER_REGISTRY-}reactclient:latest
    build:
      context: .
      dockerfile: reactclient/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - aspnetserver
    volumes:
      - ./src:/app/src
    networks:
      - postsFrontendNetwork

  #FLUENT
  fluentd:
    container_name: fluentd
    image: ${DOCKER_REGISTRY-}fluentd
    build: logging/fluentd
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - fluentd
      - elasticsearch

  #ELASTIC
  elasticsearch:
    container_name: elasticsearch
    image: ${DOCKER_REGISTRY-}elasticsearch
    build: logging/elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elasticsearch
      - kibana

  #KIBANA
  kibana:
    container_name: kibana
    image: kibana:7.17.8
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - kibana
