version: "3.4"

name: docker-compose

networks:
  postsBackendNetwork:
  postsFrontendNetwork:
  
services:
  #DATABASE
  postsbymarko.database:
    container_name: postsbymarkodb
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - 1433:1433
    networks:
      - postsBackendNetwork
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
   
  #WEB API
  postsbymarko.host:
    container_name: postsbymarkohost
    build:
      dockerfile: PostsByMarko.host/Dockerfile
    ports:
      - 7171:80
    depends_on:
      - postsbymarko.database
    networks:
      - postsBackendNetwork
      - postsFrontendNetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://host.docker.internal:7171

  #CLIENT
  postsbymarko.client:
    container_name: postsbymarkoclient
    build:
      dockerfile: PostsByMarko.Client/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postsbymarko.host
    volumes:
      - ./src:/app/src
    networks:
      - postsFrontendNetwork
    environment:
      - NODE_ENV=docker

