version: "3.4"

name: postsbymarko-docker-compose

networks:
  beNetwork:
  feNetwork:
  
services:
  #DATABASE
  sqlserver:
    container_name: PostsByMarko.SqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - 1433:1433
    networks:
      - beNetwork
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "@PostsByMarko123"
   
  #HOST
  host:
    container_name: PostsByMarko.Host
    build:
      dockerfile: src/PostsByMarko.host/Dockerfile
    ports:
      - 7171:7171
    depends_on:
      - sqlserver
    networks:
      - beNetwork
      - feNetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:7171 

  #CLIENT
  client:
    container_name: PostsByMarko.Client
    build:
      dockerfile: src/PostsByMarko.Client/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - host
    volumes:
      - ./src:/app/src
    networks:
      - feNetwork
    environment:
      - NODE_ENV=docker

