environment: development

apphost: postsaspproject

label:
  name: postsaspproject

container:
  frontEndName: reactclient
  backEndName: aspnetserver
  pullPolicy: IfNotPresent
  frontEndImage: kralmarko123/posts-client
  backEndImage: kralmarko123/posts-server
  namespace: kralmarko123 
  frontEndTag: v7
  backEndTag: v3
  frontEndport: 3000
  frontEndServiceport: 3000
  backEndport: 7171
  backEndServiceport: 7171
frontEndreplicas: 1
backEndreplicas: 1

service:
  port: 8888
  type: ClusterIP