name: PostsByMarko.Host docker workflow

on:
  push:
    branches:
      - main
    paths:
      - "src/PostsByMarko.Host/**"

  #Allow manual workflow dispatching
  workflow_dispatch:

env:
  REGISTRY: docker.io
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_NAME: postsbymarko.host
  IMAGE_TAG: 1.0.${{ github.run_number }}
  MASTER_PASSWORD: ${{ secrets.MASTER_PASSWORD }}
  SQL_PORT: ${{ vars.SQL_PORT }}
  HOST_PORT: ${{ vars.HOST_PORT }}
  CLIENT_PORT: ${{ vars.CLIENT_PORT }}
  HEADED: 0

jobs:

  run-tests:
    timeout-minutes: 20
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # - name: Run unit tests
    #   run: dotnet test ./test/PostsByMarko.UnitTests

    # - name: Run integration tests
    #   run: dotnet test ./test/PostsByMarko.IntegrationTests
    
    - name: Run frontend tests
      run: dotnet test ./test/PostsByMarko.FrontendTests

  build-and-push-to-docker:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build . --file src/PostsByMarko.Host/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin

      - name: Push Image to Docker Hub
        run: docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
