name: posts-server docker workflow

on:
  push:
    branches:
      - main
    paths:
      - "aspnetserver/**"
      - ".github/workflows/posts**"

  #Allow manual workflow dispatching
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: kralmarko123/posts-server
  IMAGE_TAG: 1.0.${{ github.run_number }}

jobs:
  Build-And-Push-To-Docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@main

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: kralmarko123
          password: nba2k13ftw

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: aspnetserver
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
