name: Docker posts-client build workflow

on:
  push:
    branches:
      - main
    paths:
      - "reactclient/**"
      - ".github/workflows/**"

  #Allow manual workflow dispatching
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build docker image
        working-directory: reactclient
        run: docker build . --file ./reactclient/Dockerfile --tag posts-aspnetserver:$(date +%s)
