name: Docker posts-server build workflow

on:
  push:
    branches:
      - main
    paths:
      - "aspnetserver/**"
      - ".github/workflows/**"

  #Allow manual workflow dispatching
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build docker image
        working-directory: aspnetserver
        run: docker build . --file Dockerfile --tag posts-aspnetserver:$(date +%s)
