name: Docker posts-aspnetserver build workflow

on:
  push:
    branches:
      - main
    paths:
      - "aspnetserver/**"
      - ".github/workflows/**"

  #Allow manual workflow dispatching
  workflow_dispatch:

env:
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: aspnetserver

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build ./aspnetserver --file ./aspnetserver/Dockerfile --tag posts-aspnetserver:$(date +%s)
